### ISSUE TITLE
onDone and onSkip callbacks aren't working in OnBoard widget, but are made mandatory.

### ISSUE THREAD

**Issue by karthikreddi** [mohanasundaramn/ms-flutter-packages#10]
**Describe the bug**
1. onDone and onSkip callbacks aren't working in OnBoard widget, but are made mandatory.
2. The following assertion was thrown during layout:
A RenderFlex overflowed by 204 pixels on the bottom.

The relevant error-causing widget was
OnBoard
lib/…/intro_screens/intro_slider_page_8.dart:12

**Expected behavior**
1. Whatever code is inserted in onDone and onSkip callbacks should be executed.
2. Check for overflow on small devices like motorola.

Remove them as there is skipButton and nextButton where the same can be achieved.

**Comment by mohanasundaramn** [comment]
- For the simple use case, `onDone` and `onSkip` callbacks need to be provided.
```dart
OnBoard(
    onBoardData: onBoardData ,
    pageController: pageController,
    onSkip: () {
      print('skipped');
    },
    onDone: () {
      print('done tapped');
    },
)
```
- For custom implementation, you can use `skipButton` and `nextButton` widgets.
- `onSkip` callback is now not a required field but either `onSkip` callback or `skipButton` needs to be provided to the OnBoard widget, else it will throw an exception.
- `onDone` callback is now not a required field but either `onDone` callback or `nextButton` needs to be provided to the OnBoard widget, else it will throw an exception.

Exception:
<img width="875" alt="Screenshot 2021-07-13 at 3 18 00 PM" src="https://user-images.githubusercontent.com/24430497/125431025-d6d2eeea-fa59-457a-a22f-b76a26af4b7e.png">

**Comment by mohanasundaramn** [comment]
@karthikreddi You can see the changes in [v1.0.1](https://pub.dev/packages/flutter_onboard/changelog)

**Comment by mohanasundaramn** [comment]
Overflow issue for the smaller devices is fixed in [V1.0.2](https://pub.dev/packages/flutter_onboard/changelog)
- Closing this issue, for now, you can reopen this issue any time, if any help required

**Comment by zionnite** [comment]
am using V2.0.0  and issue still persist, please how do i resolve this??
